### ISSUE TITLE
Keep-alive, fastcgi and unix sockets?

### ISSUE THREAD

**Issue by melroy89** [yegor-usoltsev/nginx-upstream-keepalive#1]
First of all, thank you so much for this demo repository!

What about `fastcgi_keep_conn on;` and keep-alive when using an unix socket file (eg. `server unix:... sock;`)?

Do you also need to set keep-alive on socket files? Does that even make sense? The Nginx documentation doesn't explain this at all.. So for PHP FPM you have an option called `fastcgi_keep_conn on;` to keep fastcgi connection open. It's unclear what to do when using socket files under GNU/Linux. 

See also (unanswered for 2 years): https://forum.nginx.org/read.php?11,294938,294938

Thanks!

Regards,
Melroy van den Berg

**Comment by yegor-usoltsev** [comment]
While I am not an expert in NGINX, Unix, or PHP, here is what I understand about the performance considerations:

Unix sockets are usually faster than TCP sockets for communicating between processes on the same host since Unix sockets avoid the network stack entirely. You still can use `keepalive` with Unix sockets, but the performance difference will be minor.

And definitely do not turn off the `fastcgi_keep_conn`.

Here would be a very simple NGINX configuration:

```nginx
server {
  listen 80;
  index index.php;
  root /var/www/html;
  location ~ \.php$ {
    fastcgi_pass php_backend;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_keep_conn on;
  }
}

upstream php_backend {
  server unix:/var/run/php/php-fpm.sock;
  # server 127.0.0.1:9000; # You can combine TCP servers and Unix sockets in "upstream" block
  keepalive 8;
}
```

For further best practices, you can have a look at DigitalOcean's [NGINXConfig](https://www.digitalocean.com/community/tools/nginx) tool.

**Comment by melroy89** [comment]
Yea so now my question was: will do keepalive 8 do something here at all? When using a socket file.

**Comment by yegor-usoltsev** [comment]
If you’re looking for a straightforward answer, here it is: **it depends**.

Here’s what I found from testing different setups on my machine:

1. Unix sockets are generally a bit faster than TCP sockets.
2. Enabling `fastcgi_keep_conn` and `keepalive` provides a measurable performance boost.
3. This improvement is more noticeable with TCP sockets than with Unix sockets.

Here are the numbers:

| **Test case**                                    | **RPS**           | **Latency**  |
| ------------------------------------------------ | ----------------- | ------------ |
| **TCP / fastcgi_keep_conn OFF / keepalive OFF**  | 8791.1 ± 161.45   | 225µs ± 48µs |
| **TCP / fastcgi_keep_conn ON / keepalive OFF**   | 8514.02 ± 79.07   | 232µs ± 45µs |
| **TCP / fastcgi_keep_conn ON / keepalive ON**    | 10356.21 ± 115.86 | 190µs ± 51µs |
| **Unix / fastcgi_keep_conn OFF / keepalive OFF** | 9571.68 ± 66.48   | 206µs ± 40µs |
| **Unix / fastcgi_keep_conn ON / keepalive OFF**  | 9376.97 ± 73.16   | 211µs ± 42µs |
| **Unix / fastcgi_keep_conn ON / keepalive ON**   | 10333 ± 155.5     | 191µs ± 65µs |

While I won’t be providing the source code, I strongly encourage you to do your own testing to get the most accurate results in your environment.
